import assert from 'node:assert/strict';
import {createGame, build, repair, upgrade, advance, findPath, free, movePlayer, stopPlayer, startAssault, stopAssault, placement, blink, GATE, info} from './game.mjs';
const run = (s, seconds) => { for (let i=0;i<Math.ceil(seconds/.05);i++) advance(s,.05); };
const s = createGame();
assert.equal(s.test,null,'默认场景没有巨魔与 AI');
assert(findPath(s,{x:900,y:432},{x:410,y:432}),'无墙时入口可通行');
assert.equal(build(s,'wall',GATE.x,GATE.y),'');
let wall=s.buildings[0];
assert(!wall.started,'放置后精灵需要先走近');
run(s,.2);assert(wall.progress<1,'建筑不能瞬间完成');
run(s,10);assert.equal(wall.progress,1,'施工可完成');
assert.equal(findPath(s,{x:900,y:432},{x:410,y:432}),null,'实体墙必须封死所有入口路径');
assert(!free(s,GATE.x,GATE.y),'墙占地不可站立');
assert(placement(s,'wall',GATE).error.includes('一堵'),'一座主墙上限');
assert(movePlayer(s,{x:900,y:432}).includes('封住'),'玩家寻路也不能穿墙');
assert(movePlayer(s,{x:750,y:200}).includes('树林'),'不能穿越森林');
assert.equal(upgrade(s,wall),'');run(s,2);
assert.equal(findPath(s,{x:900,y:432},{x:410,y:432}),null,'升级过程中墙仍然阻挡');
run(s,5);assert.equal(wall.level,1);
s.gold=500;assert.equal(upgrade(s,wall),'','升级只需点一下，不必精灵到场');
movePlayer(s,{x:250,y:375});run(s,1);assert(wall.upgrade,'精灵走开也不取消升级');
run(s,3);assert.equal(wall.level,2,'建筑自行完成升级，不需要精灵');
const towerGame=createGame();build(towerGame,'tower',464,384);run(towerGame,10);
assert(repair(towerGame,towerGame.buildings[0]).includes('不必手工修理'),'只有墙需要精灵动手修理');
wall.hp=100;movePlayer(s,{x:250,y:375});run(s,3);
const hp=wall.hp,gold=s.gold;
assert.equal(repair(s,wall),'');run(s,.15);
assert.equal(wall.hp,hp,'远处发修理命令不能立即回血');
run(s,3);assert(wall.hp>hp,'靠近后才能持续修理');assert(s.gold<gold,'修理按时间扣金');
stopPlayer(s);const stopped=wall.hp;run(s,1);assert.equal(wall.hp,stopped,'停止指令必须中止修理');
wall.hp=info(wall).hp;startAssault(s);run(s,8);
assert(s.test.x>GATE.x+GATE.halfW,'巨魔必须停在墙外');
assert(wall.hp<info(wall).hp,'巨魔能在外侧伤害墙');
assert.equal(findPath(s,s.test,{x:410,y:432}),null);
wall.hp=1;run(s,7);assert.equal(wall.hp,0,'墙可被击毁');
assert(s.test.x<GATE.x,'墙毁后巨魔才通过入口');
stopAssault(s);assert.equal(build(s,'wall',GATE.x,GATE.y),'','墙毁后可重建');run(s,10);
assert.equal(findPath(s,{x:900,y:432},{x:410,y:432}),null,'重建后恢复封路');
assert.equal(blink(s,{x:655,y:432}),'','闪烁可越过主墙至合法地面');
assert.equal(blink(s,{x:500,y:430}),'闪烁冷却中');
const houseGame=createGame();assert.equal(build(houseGame,'house',272,336),'');run(houseGame,10);
assert(houseGame.income===2&&houseGame.gold>120,'只有建成的房屋产金');
console.log('通过：窄口阻挡、无绕路、破墙通行、重建/升级碰撞、施工时序、近身持续修理、中断与扣费、闪烁、产金。');
